[ticket/16787] Properly check if fsockopen() is enabled - PHP 8
phpbb/phpbb pull request #6222
Opened 2021-05-29 19:12 UTC by 3D-I

PHPBB3-16787

Checklist:

- [x] Correct branch: master for new features; 3.3.x for fixes
- [ ] Tests pass
- [x] Code follows coding guidelines: [master](https://area51.phpbb.com/docs/dev/master/development/coding_guidelines.html) and [3.3.x](https://area51.phpbb.com/docs/dev/3.3.x/development/coding_guidelines.html)
- [x] Commit follows commit message [format](https://area51.phpbb.com/docs/dev/3.3.x/development/git.html)

https://tracker.phpbb.com/browse/PHPBB3-16787

2021-05-29 19:34 UTC, 3D-I commented
I'm not sure I understand the problem with the test, as usual.

2021-05-29 19:52 UTC, marc1706 requested changes

2021-05-29 19:52 UTC, marc1706 commented on phpBB/phpbb/file_downloader.php
> +			$socket = fsockopen(($port == 443 ? 'ssl://' : '') . $host, $port, $this->error_number, $this->error_string, $timeout)
Add this back:
```suggestion
			$socket = @fsockopen(($port == 443 ? 'ssl://' : '') . $host, $port, $this->error_number, $this->error_string, $timeout)
```

2021-05-30 01:01 UTC, rubencm commented
Can that be just replaced by file_get_contents?, is much simpler

2021-05-30 23:22 UTC, 3D-I commented
> 
> 
> Can that be just replaced by file_get_contents?, is much simpler
> Edit: Do we really need a class for this?

In a perfect world I would say that the use of different file reading techniques should be used, using code that automatically knows which one to use for each server configuration (cURL, file_get_contents, fsockopen etc...) or something like Guzzle in case. This before having to give a negative response and show an error to the end user. This PR proposes the solution for the problem highlighted by the ticket itself, only. As for the class, I would say that this is a question @marc1706 can answer as he is the one who wrote it 7 years ago.

2021-05-31 05:21 UTC, marc1706 commented
This class replaces the original get_remote_file() function we had. So yes, moving this to a class was a viable step. Back then Guzzle was not an option yet. It could make sense to move this to use something like Guzzle, however that is outside the scope of this ticket and hence will require a new one.

2021-06-05 20:23 UTC, marc1706 approved these changes

2021-06-05 20:24 UTC, merged

2021-06-06 03:12 UTC, 3D-I commented
> 
> 
> ... however that is outside the scope of this ticket and hence will require a new one.

Perhaps this ticket could be used on purpose.
https://tracker.phpbb.com/browse/PHPBB3-16738