[Ticket/12426] Allow search by custom profile fields
phpbb/phpbb pull request #6287
Opened 2021-09-08 02:17 UTC by satanasov

Checklist:

- [ ] Correct branch: master for new features; 3.3.x for fixes
- [ ] Tests pass
- [ ] Code follows coding guidelines: [master](https://area51.phpbb.com/docs/dev/master/development/coding_guidelines.html) and [3.3.x](https://area51.phpbb.com/docs/dev/3.3.x/development/coding_guidelines.html)
- [ ] Commit follows commit message [format](https://area51.phpbb.com/docs/dev/3.3.x/development/git.html)

Tracker ticket (set the ticket ID to 12426):

https://tracker.phpbb.com/browse/PHPBB3-12345

2021-09-08 02:31 UTC, 3D-I requested changes
First read - beside that there are also `phpBB > sniff` issues.

https://github.com/phpbb/phpbb/pull/6287/checks?check_run_id=3540084770

2021-09-08 02:31 UTC, 3D-I commented on phpBB/cache/index.htm
> -<html>
Why has been deleted?

2021-09-08 02:31 UTC, 3D-I commented on phpBB/memberlist.php
> +		$sql_from = array();
pls use short array syntax `[]`

2021-09-08 02:31 UTC, 3D-I commented on phpBB/memberlist.php
> +				$sql_from = array(
pls use short array syntax `[]`

2021-09-08 02:31 UTC, 3D-I commented on phpBB/memberlist.php
> +			$sql_join[] = array(
pls use short array syntax `[]`

2021-09-08 02:31 UTC, 3D-I commented on phpBB/memberlist.php
> +		$sql_array = array(
pls use short array syntax `[]`

2021-09-08 02:31 UTC, 3D-I commented on phpBB/memberlist.php
> +		$sql_array = array(
pls use short array syntax `[]`

2021-09-08 02:31 UTC, 3D-I commented on phpBB/phpbb/profilefields/manager.php
> +	* Check if there is any record in CUSTOM_PROFILE_FILEDS_DATA
typo

2021-09-08 02:31 UTC, 3D-I commented on phpBB/phpbb/profilefields/manager.php
> +		$custom_search_array = array();
pls use short array syntax `[]`

2021-09-08 02:31 UTC, 3D-I commented on phpBB/phpbb/profilefields/type/type_base.php
> +		$this->template->set_filenames(array(
pls use short array syntax `[]` - all over ;)

2021-09-08 02:45 UTC, satanasov commented on phpBB/cache/index.htm
> -<html>
I don't know really ... apparently by mistake.

2021-09-08 03:14 UTC, 3D-I commented on phpBB/memberlist.php
> +				$sql_array = array(
pls use short array syntax `[]`

2021-09-08 03:15 UTC, 3D-I commented on phpBB/phpbb/profilefields/manager.php
> +	* Check for data in CUSTOM_PROFILE_FILEDS_DATA
typo

should be `CUSTOM_PROFILE_FIELDS_DATA`

2021-09-08 03:26 UTC, 3D-I commented on phpBB/phpbb/profilefields/manager.php
>  	* @return boolean
Type return should be `bool`

2021-09-08 22:06 UTC, DavidIQ commented on phpBB/memberlist.php
> +		if (!empty($sql_from))
`count` is the typical way we check for arrays having any elements.

2021-09-08 22:16 UTC, 3D-I commented on phpBB/memberlist.php
> +			//);
IMHO those three commented lines should be removed.

2021-09-08 22:25 UTC, 3D-I commented on phpBB/phpbb/profilefields/type/type_date.php
> +		$output = array(
Short array syntax pls

2021-09-08 22:25 UTC, 3D-I commented on phpBB/phpbb/profilefields/type/type_dropdown.php
> +			$this->template->assign_block_vars('dropdown.options', array(
Short array syntax pls

2021-09-08 22:26 UTC, 3D-I commented on phpBB/phpbb/profilefields/type/type_dropdown.php
> +		$output = array(
Short array syntax pls

2021-09-08 22:26 UTC, 3D-I commented on phpBB/phpbb/profilefields/type/type_int.php
> +		$output = array(
Short array syntax pls

2021-09-08 22:58 UTC, 3D-I commented
@satanasov you need to fix this commit messages _(use the usual commit template)_

![image](https://user-images.githubusercontent.com/480857/132596090-3575ee91-b06e-416a-b7d8-7a4a8a62966c.png)


![image](https://user-images.githubusercontent.com/480857/132596125-bc8f0502-7b56-4a80-9c6c-4668c5612f64.png)


---

And here, where `Ticket` should be `ticket`

![image](https://user-images.githubusercontent.com/480857/132596418-03fe2f9b-d1fd-4882-b0dd-c4d7191badaa.png)

2021-09-08 23:29 UTC, 3D-I commented on phpBB/phpbb/profilefields/type/type_dropdown.php
>  		$profile_row[0] = array(
should be `$profile_row[0] = [`

2021-09-08 23:30 UTC, satanasov commented on phpBB/phpbb/profilefields/type/type_dropdown.php
>  		$profile_row[0] = array(
Merge resolution issue. Fixed.

2021-09-09 00:29 UTC, satanasov commented
Closing for the moment ... will redo in a bit.

2021-09-09 00:29 UTC, closed without merging