[ticket/16904] Fix regression in MCP for topics selection
phpbb/phpbb pull request #6323
Opened 2021-11-02 06:58 UTC by rxu

Regression was introduced in #5760.

Checklist:

- [ ] Correct branch: master for new features; 3.3.x for fixes
- [ ] Tests pass
- [ ] Code follows coding guidelines: [master](https://area51.phpbb.com/docs/master/coding-guidelines.html) and [3.3.x](https://area51.phpbb.com/docs/dev/3.3.x/development/coding_guidelines.html)
- [ ] Commit follows commit message [format](https://area51.phpbb.com/docs/dev/3.3.x/development/git.html)

<a href="https://tracker.phpbb.com/browse/PHPBB3-16904">PHPBB3-16904</a>.

2021-11-02 06:58 UTC, rxu commented
Currently this PR also changes behavior of `function phpbb_extra_url()` so that its resulting string is not being prepended with `&amp`.

2021-11-07 10:14 UTC, marc1706 requested changes

2021-11-07 10:14 UTC, marc1706 commented on tests/functional/mcp/mcp_main_test.php
> +		$mcp_link = substr_replace($crawler->selectLink($this->lang('MCP_SHORT'))->attr('href'), '', 0, 2); // Remove leading ./
How about just using:
```
$crawler = self::$client->click($crawler->selectLink($this->lang('MCP_SHORT'))->link());
```

2021-11-07 10:14 UTC, marc1706 commented on tests/functional/mcp/mcp_main_test.php
> +		$mcp_link = substr_replace($crawler->selectLink($this->lang('MCP_SHORT'))->attr('href'), '', 0, 2); // Remove leading ./
See above comment.

2021-11-07 10:14 UTC, marc1706 commented on tests/functional/mcp/mcp_main_test.php
> +				)->attr('href'), '', 0, 2); // Remove leading ./
As stated above, there is a better way than trying to do substr_replace() ;)

2021-11-07 10:14 UTC, marc1706 commented on tests/functional/mcp/mcp_test.php
> +		$mcp_link = substr_replace($crawler->selectLink($this->lang('MCP_SHORT'))->attr('href'), '', 0, 2); // Remove leading ./
Same as in the mcp_main_test

2021-11-07 10:19 UTC, rxu commented on tests/functional/mcp/mcp_main_test.php
> +				// Fork or move the topic to the forum id=3 'Download #1'
Shall I create a forum just for that?

2021-11-23 19:39 UTC, CHItA approved these changes

2021-11-23 20:52 UTC, marc1706 approved these changes

2021-11-23 22:07 UTC, marc1706 commented
@rxu could you create a PR to resolve the merge conflicts with master? right now it does not properly merge into master and I won't have time to have a look until beginning of next week.

2021-11-24 07:33 UTC, rxu commented
@marc1706 Done.

2021-11-30 20:47 UTC, merged