[ticket/16912] Rewrite email headers encoding method
phpbb/phpbb pull request #6332
Opened 2021-11-23 08:17 UTC by rxu

Alternative to #6327.
Based on symfony/polyfill-iconv implementations.

Checklist:

- [ ] Correct branch: master for new features; 3.3.x for fixes
- [ ] Tests pass
- [ ] Code follows coding guidelines: [master](https://area51.phpbb.com/docs/master/coding-guidelines.html) and [3.3.x](https://area51.phpbb.com/docs/dev/3.3.x/development/coding_guidelines.html)
- [ ] Commit follows commit message [format](https://area51.phpbb.com/docs/dev/3.3.x/development/git.html)

Tracker ticket (set the ticket ID to **your ticket ID**):

https://tracker.phpbb.com/browse/PHPBB3-12345

2021-12-13 20:43 UTC, marc1706 commented
Can you quickly elaborate how your PR compared to #6327 and #6320?
Btw, I did also restart your tests.

2021-12-14 02:47 UTC, rxu commented
@marc1706 If merged, current PR will make #6327 obsoleted.
As for #6320, it will add config switch allowing to turn `US-ASCII` encoding off to always use `Base64` headers encoding (pretty much like it behaved before #6258).

2021-12-14 03:11 UTC, 3D-I commented
^^ As per above, there is one line of code that could be not important there in my PR once this PR will be merged. I will be more than glad to do some testing then and modify it accordingly, in case.

2021-12-23 20:10 UTC, marc1706 requested changes
Rest looks fine.

2021-12-23 20:10 UTC, marc1706 commented on phpBB/includes/functions_messenger.php
> +	if ('' !== $line_data)
```suggestion
	if ($line_data !== '')
```

2022-01-12 20:18 UTC, merged