[ticket/16978] add missing ul closeing tag
phpbb/phpbb pull request #6378
Opened 2022-04-05 16:52 UTC by hanakin

Checklist:

- [x] Correct branch: master for new features; 3.3.x for fixes
- [ ] Tests pass
- [x] Code follows coding guidelines: [master](https://area51.phpbb.com/docs/master/coding-guidelines.html) and [3.3.x](https://area51.phpbb.com/docs/dev/3.3.x/development/coding_guidelines.html)
- [x] Commit follows commit message [format](https://area51.phpbb.com/docs/dev/3.3.x/development/git.html)

Tracker ticket (set the ticket ID to **your ticket ID**): PHPBB3-16978

https://tracker.phpbb.com/browse/PHPBB3-16978

2022-04-05 16:56 UTC, 3D-I commented
Good cacth! 💯 

What about to port to **Twig** the whole block in the meantime?

2022-04-05 17:55 UTC, hanakin commented
might as well just do the whole file... been a while since attempting to convert stuff will need a thorough review ;)

2022-04-05 23:43 UTC, 3D-I requested changes
First quick review.

2022-04-05 23:43 UTC, 3D-I commented on phpBB/styles/prosilver/template/posting_pm_header.html
> +				<label for="group_list"><strong>{{ lang('TO_ADD_GROUPS') }}{{ lang('COLON') }}</strong></label><br />
`<br />` should be `<br>` - applies to the whole file.

2022-04-05 23:43 UTC, 3D-I commented on phpBB/styles/prosilver/template/posting_pm_header.html
> +					<dt><label><strong>{{ lang('TO_ADD_MASS') }}{{ lang('COLON') }}</strong><textarea id="username_list" name="username_list" class="inputbox" cols="50" rows="2" tabindex="1"></textarea></label></dt
Please use `{{ lang('') ~ lang('COLON') }}` - applies to the whole file.

2022-04-05 23:43 UTC, 3D-I commented on phpBB/styles/prosilver/template/posting_pm_header.html
> +						<input type="submit" name="add_to" value="{{ lang('ADD') }}" class="button2" tabindex="1" />
Void elements should be closed with a simple `>` instead of ` />` - applies to the whole file.

2022-04-05 23:43 UTC, 3D-I commented on phpBB/styles/prosilver/template/posting_pm_header.html
> +				<hr />
`<hr>` please

2022-04-11 19:15 UTC, marc1706 commented
I would actually split this off. For 3.3 add the missing tag, for master we can then change everything to twig. I can also split it up for you.

2022-04-11 23:19 UTC, hanakin commented
Im currently traveling so will not get to it for a couple days

2022-04-12 11:04 UTC, marc1706 commented
Ok, then I'll have a look at splitting this up.

2022-06-06 07:45 UTC, merged