[ticket/17151] Make macros available for extensions
phpbb/phpbb pull request #6530
Opened 2023-09-09 07:04 UTC by rxu

Also add tests and error reporting.

PHPBB3-17151

Checklist:

- [ ] Correct branch: master for new features; 3.3.x for fixes
- [ ] Tests pass
- [ ] Code follows coding guidelines: [master](https://area51.phpbb.com/docs/master/coding-guidelines.html) and [3.3.x](https://area51.phpbb.com/docs/dev/3.3.x/development/coding_guidelines.html)
- [ ] Commit follows commit message [format](https://area51.phpbb.com/docs/dev/3.3.x/development/git.html)

Tracker ticket:

https://tracker.phpbb.com/browse/PHPBB3-17151

2023-09-09 07:05 UTC, rxu commented
Also currently forms macros is not used for building `select`s, but that can be resolved later in a separate PR.

2023-09-10 19:43 UTC, marc1706 requested changes

2023-09-10 19:43 UTC, marc1706 commented on tests/functional/fixtures/ext/foo/bar/styles/prosilver/template/foobar_mcp.html
> +<!-- INCLUDE overall_header.html -->
Should use twig syntax instead

2023-09-10 19:43 UTC, marc1706 commented on tests/functional/fixtures/ext/foo/bar/mcp/main_info.php
> +		return array(
Short array syntax in this file

2023-09-10 19:43 UTC, marc1706 commented on tests/functional/fixtures/ext/foo/bar/ucp/main_info.php
>  		return array(
Would also opt for changing this file to short array syntax while you're changing it

2023-09-16 08:10 UTC, marc1706 approved these changes

2023-09-16 08:10 UTC, merged