Ticket/17333 UX Enhancements for Web Push Subscribing
phpbb/phpbb pull request #6632
Opened 2024-06-04 17:17 UTC by iMattPro

Checklist:

- [ ] Correct branch: master for new features; 3.3.x for fixes
- [ ] Tests pass
- [ ] Code follows coding guidelines: [master](https://area51.phpbb.com/docs/master/coding-guidelines.html) and [3.3.x](https://area51.phpbb.com/docs/dev/3.3.x/development/coding_guidelines.html)
- [ ] Commit follows commit message [format](https://area51.phpbb.com/docs/dev/3.3.x/development/git.html)

Tracker ticket:

https://tracker.phpbb.com/browse/PHPBB-17333

2024-06-05 16:05 UTC, iMattPro commented
@marc1706 This currently sets these new configs to false by default. Thus retaining the current user experience. But, should they be on by default instead? Having both these enabled does improve the discoverability of the push notification feature.

2024-06-05 19:12 UTC, marc1706 commented
I'd go with yes by default and of course only showing it once push notifications have been enabled.

2024-06-06 01:49 UTC, iMattPro commented
> I'd go with yes by default and of course only showing it once push notifications have been enabled.

LOL. I forgot I already set these vars to be enabled by default. And ofc they don't show if web push is disabled. But I did take this opportunity to optimize the code a little so that it won't really won't execute any extra stuff if web push is disabled in general.

2024-06-06 14:21 UTC, marc1706 commented
> > I'd go with yes by default and of course only showing it once push notifications have been enabled.
> 
> LOL. I forgot I already set these vars to be enabled by default. And ofc they don't show if web push is disabled. But I did take this opportunity to optimize the code a little so that it won't really won't execute any extra stuff if web push is disabled in general.
> 
> Failing test is a scam LOL

I've restarted the test :)

2024-06-06 18:32 UTC, marc1706 requested changes

2024-06-06 18:32 UTC, marc1706 commented on phpBB/includes/acp/acp_board.php
> +						'webpush_method_enables'	=> ['lang' => 'WEBPUSH_METHOD_ENABLES', 'validate' => 'bool', 'type' => 'radio:yes_no', 'explain' => true],
How about:
```suggestion
						'webpush_method_default_enable'	=> ['lang' => 'WEBPUSH_METHOD_DEFAULT_ENABLE', 'validate' => 'bool', 'type' => 'radio:yes_no', 'explain' => true],
```

2024-06-06 18:32 UTC, marc1706 commented on phpBB/includes/functions.php
> +			&& $template->retrieve_var('NOTIFICATIONS_WEBPUSH_ENABLE') === null)
```suggestion
		if ($config['webpush_enable'] && $config['webpush_dropdown_subscribe']
			&& $template->retrieve_var('NOTIFICATIONS_WEBPUSH_ENABLE') === null)
```

2024-06-06 18:32 UTC, marc1706 commented on phpBB/includes/functions.php
> +				$formHelper = $phpbb_container->get('form_helper');
```suggestion
				$form_helper = $phpbb_container->get('form_helper');
```

2024-06-06 18:32 UTC, marc1706 commented on phpBB/includes/functions.php
> +				$template_ary = $webpush['method']->get_ucp_template_data($controller_helper, $formHelper);
No need for an extra variable, just stick it directly to assign_vars ;)

2024-06-07 18:10 UTC, marc1706 approved these changes

2024-06-07 18:11 UTC, merged