[ticket/17382] Update the find a member FAQ text to fix grammar
phpbb/phpbb pull request #6704
Opened 2024-08-12 20:22 UTC by danieltj27

Updated the text of an answer on the FAQ page that explained how
to search for members on the forum. Originally the text read as
`Visit to the “Members” page` which is grammatically incorrect,
specifically `visit to the`.

PHPBB-17382

Checklist:

- [x] Correct branch: master for new features; 3.3.x for fixes
- [x] Tests pass
- [x] Code follows coding guidelines: [master](https://area51.phpbb.com/docs/master/coding-guidelines.html) and [3.3.x](https://area51.phpbb.com/docs/dev/3.3.x/development/coding_guidelines.html)
- [x] Commit follows commit message [format](https://area51.phpbb.com/docs/dev/3.3.x/development/git.html)

Tracker ticket:

https://tracker.phpbb.com/browse/PHPBB-17382

2024-08-12 22:34 UTC, Noxwizard commented
I agree the spurious "to" should be removed, but I don't agree with the rest. I would suggest changing it to: `Visit the memberlist and click the “Find a member” link.`

We're pretty consistent about using double quotes for referencing text on the page and the actions for following a link are either "click" or "follow" with us typically using "click". "Select" would be used for dropdown menus, checkboxes, or radio buttons.

2024-09-10 19:51 UTC, marc1706 requested changes

2024-09-10 19:51 UTC, marc1706 commented on phpBB/language/en/help/faq.php
> +	'HELP_FAQ_SEARCH_MEMBERS_ANSWER'	=> 'Visit the members page and select the \'Find a member\' link.',
I would keep the unicode quotation marks and just remove the `to`.

2024-09-29 22:39 UTC, danieltj27 commented
Updated text to what was suggested by @Noxwizard.

2024-09-30 19:04 UTC, marc1706 approved these changes

2024-09-30 19:05 UTC, merged